In [ ]:
#NumPy:""is a Python library used to work with numbers, arrays, and mathematical calculations quickly and easily.""
#NumPy is a library used for fast calculations and working with arrays in Python.
"""Main Uses of NumPy
Mathematical operations
Array handling
Matrix calculations
Statistics
Linear algebra
AI/ML preprocessing
Deep Learning computations
Data Science projects """
#Important NumPy Functions
"""Function	Use
np.array()	Create array
np.zeros()	Create zeros
np.ones()	Create ones
np.arange()	Create range
np.linspace()	Equal spacing
np.reshape()	Change shape
np.random.rand()	Random floats
np.random.randint()	Random integers
np.mean()	Average
np.sum()	Total
np.max()	Maximum
np.min()	Minimum
np.dot()	Matrix multiplication"""


In [3]:
#1. Create an Array
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)
print(np.shape(arr))
print(np.size(arr))

[10 20 30 40 50]
(5,)
5


In [1]:
#Check Array Type
import numpy as np
arr=np.array([10,20,30,40,50])
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
#3.Array Dimensions
#1D Array
import numpy as np
arr=np.array([10,20,30,40])
print(arr.ndim)
#2D Array
import numpy as np
arr=np.array([
    [10,20,30,40,50],
    [60,70,80,90,100]
])
print(arr.ndim)
print(arr.shape)
print(arr.size)

1
2
(2, 5)
10


In [6]:
#4. Create Zeros Array
import numpy as np
arr=np.zeros([2,3])
print(arr)
#5. Create One Array
import numpy as np
arr=np.ones([2,3])
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
#5.Range of the array
import numpy as np
arr=np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [4]:
#np.random.rand()	Random floats
import numpy as np
arr=np.random.rand(3,4)
print(arr)
print(np.random.randint(1,10,size=(3,3)))
print(arr)

[[0.20006967 0.1202822  0.19432664 0.32693143]
 [0.51869684 0.76081849 0.97060905 0.01235562]
 [0.80404244 0.40326647 0.40857583 0.11549479]]
[[6 8 3]
 [8 4 5]
 [8 6 8]]
[[0.20006967 0.1202822  0.19432664 0.32693143]
 [0.51869684 0.76081849 0.97060905 0.01235562]
 [0.80404244 0.40326647 0.40857583 0.11549479]]


In [8]:
#6. Reshape Array
import numpy as np
arr=np.array([10,20,30,40,50,60])
new_arr=arr.reshape(2,3)
print(new_arr)

[[10 20 30]
 [40 50 60]]


In [3]:
#7. Mathematical Operations
import numpy as np
a=np.array([10,20,30,40,50])
b=np.array([60,70,80,90,100])
print(a+b)
print(a-b)
print(a*b)

[ 70  90 110 130 150]
[-50 -50 -50 -50 -50]
[ 600 1400 2400 3600 5000]


In [9]:
#Student Marks Analysis
import numpy as np
marks=([60,70,80,90,100])
print("marks:",marks)
print("max:",np.max(marks))
print("min:",np.min(marks))
print("Average:",np.mean(marks))
print("median:",np.median(marks))


marks: [60, 70, 80, 90, 100]
max: 100
min: 60
Average: 80.0
median: 80.0


In [10]:
#2D array (matrix)
import numpy as np
score=np.array([
    [10,20,30,40,50],
    [60,70,80,90,100]
])
print("shape:",np.shape(score))
print("column avg:",np.mean(score,axis=0))
print("row avg:",np.mean(score,axis=1))

shape: (2, 5)
column avg: [35. 45. 55. 65. 75.]
row avg: [30. 80.]


In [1]:
#Reshape
import numpy as np
arr=np.array([10,20,30,40,60,70,80,90])
new_arr=arr.reshape(2,4)
print(new_arr)

[[10 20 30 40]
 [60 70 80 90]]


In [11]:
#Array Indexing & Slicing
import numpy as np

arr = np.array([10,20,30,40,50,60])

print("Array:", arr)

# Indexing
print("First Element:", arr[0])
print("Third Element:", arr[2])

# Slicing
print("Elements from index 1 to 4:", arr[1:5])
print("First 3 Elements:", arr[:3])
print("Last 2 Elements:", arr[-2:])

Array: [10 20 30 40 50 60]
First Element: 10
Third Element: 30
Elements from index 1 to 4: [20 30 40 50]
First 3 Elements: [10 20 30]
Last 2 Elements: [50 60]


In [5]:
#1. Dot Product of 1D Arrays (Vectors) :is used to calculate the dot product of two arrays.
import numpy as np
arr1=np.array([10,20,30,40,50])
arr2=np.array([60,70,80,90,100])
result=np.dot(arr1,arr2)
print(result)

13000


In [7]:
import numpy as np
arr1=np.array([[1,2],
              [3,4]])
arr2=np.array([[5,6],
              [7,8]])
result=np.dot(arr1,arr2)
print(result)

[[19 22]
 [43 50]]
